# -*- coding: utf-8 -*-
"""GestionCalificaciones10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QD-cs-AYI8d3R5t6BoEsMsUP_dHSiS-i
"""

class GestionCalificaciones:
    def __init__(self):
        # Inicializamos las listas y variables que usaremos.
        self.nombres = []
        self.calificaciones = []
        self.promedio_grupal = 0.0
        self.alumnos_destacados = []
        self.contador_alumnos = 0

    def leer_datos(self):
        """
        Este método pide al usuario los nombres y calificaciones de 10 alumnos.
        Valida las entradas usando una función recursiva para evitar bucles.
        """
        if self.contador_alumnos < 10:
            nombre = input(f"Ingresa el nombre del alumno {self.contador_alumnos + 1}: ")
            self.nombres.append(nombre)
            self._pedir_calificacion(nombre)
            self.contador_alumnos += 1
            self.leer_datos()  # Llamada recursiva para el siguiente alumno
        else:
            print("\nDatos leídos correctamente.\n")

    def _pedir_calificacion(self, nombre_alumno):
        """
        Función auxiliar para pedir y validar la calificación de un alumno de forma recursiva.
        """
        calificacion_str = input(f"Ingresa la calificación de {nombre_alumno} (0-10): ")
        if calificacion_str.replace('.', '', 1).isdigit():
            calificacion = float(calificacion_str)
            if 0 <= calificacion <= 10:
                self.calificaciones.append(calificacion)
            else:
                print("La calificación debe estar entre 0 y 10. Por favor, intenta de nuevo.")
                self._pedir_calificacion(nombre_alumno)  # Recursión para reintentar
        else:
            print("Entrada no válida. Por favor, ingresa un número.")
            self._pedir_calificacion(nombre_alumno)  # Recursión para reintentar

    def realizar_proceso(self):
        """
        Este método calcula el promedio grupal y encuentra a los alumnos destacados.
        """
        if not self.calificaciones:
            print("No hay calificaciones para procesar. Por favor, lee los datos primero.")
            return

        # Sumamos todas las calificaciones y las dividimos por el número de alumnos.
        self.promedio_grupal = sum(self.calificaciones) / len(self.calificaciones)

        # Recorremos la lista de calificaciones para encontrar a los alumnos con más de 9.5.
        self.alumnos_destacados = []
        for i, calificacion in enumerate(self.calificaciones):
            if calificacion > 9.5:
                self.alumnos_destacados.append(self.nombres[i])

    def imprimir_resultados(self):
        """
        Este método muestra los resultados finales de una manera clara.
        """
        print("\n--- Resultados ---")
        if not self.calificaciones:
            print("No hay resultados para mostrar. Por favor, lee y procesa los datos primero.")
            return

        print(f"Promedio grupal de calificaciones: {self.promedio_grupal:.2f}")

        if self.alumnos_destacados:
            print("\nAlumnos con promedio mayor a 9.5:")
            for alumno in self.alumnos_destacados:
                print(f"- {alumno}")
        else:
            print("\nNo hay alumnos con calificaciones superiores a 9.5.")

# --- Ejemplo de cómo usar la clase en Google Colab ---
# Crea una instancia de la clase
gestion = GestionCalificaciones()

# Llama a los métodos en el orden correcto
gestion.leer_datos()
gestion.realizar_proceso()
gestion.imprimir_resultados()