# -*- coding: utf-8 -*-
"""Te damos la bienvenida a Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

class Triangulo:

    def __init__(self):
        self.base = 0.0
        self.altura = 0.0
        self.area = 0.0

    def leer_mensajes(self):
        print("Este programa calcula el área de un triángulo.")
        self.base = float(input("Escribe la longitud de la base: "))
        self.altura = float(input("Escribe la altura: "))


    def calcular_area(self):
        self.area = (self.base * self.altura) / 2

    # Método para mostrar el resultado final
    def imprimir_resultados(self):
        print("\n--- Resultados ---")
        print(f"Base: {self.base}")
        print(f"Altura: {self.altura}")
        print(f"El área del triángulo es: {self.area}")

# Creamos un objeto de la clase Triangulo
Mi_triangulo = Triangulo()

# Llamamos a los métodos en el orden que se deben ejecutar
Mi_triangulo.leer_mensajes()
Mi_triangulo.calcular_area()
Mi_triangulo.imprimir_resultados()